CREATE TABLE estudiantes
id_estudiante serial PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
correo VARCHAR(100) NOT NULL UNIQUE,

CREATE TABLE cursos
id_curso SERIAL PRIMARY KEY
nombre VARCHAR(100) NOT NULL,


CREATE TABLE matriculas
id_matricula SERIAL PRIMARY KEY
id_estudiante INT NOT NULL,
fecha_matricula DATE NOT NULL
FOREIGN KEY (id_estudiante) REFERENCES estudiantes(id_estudiante)
FOREIGN KEY (id_curso) REFERENCES cursos(id_curso)

Foreign Key (id_estudiante) REFERENCES estudiantes (id_estudiante)

//SI SE ELIMINA UN ESTUDIANTE, SE ELIMINARAN AUTOMACTICAMENTE TODAS SUS MATRICULAS ON DELETE CASCADE)

//SI SE ACTUALIZA EL ID_ESTUDIANTE EN LA TABLA ESTUDIANTE, SE ACTUALIZARA AUTOMATICAMENTE EN LA TABLA MATRICULAS ON UPDATE CASCADE)